### ISSUE TITLE
save() got an unexpected keyword argument 'max_length'

### ISSUE THREAD

**Issue by SamambaMan** [ecometrica/django-hashedfilenamestorage#5]
I'm using django 1.10 and I get this error when trying to save. 
Is there any imadiate workaround i may do to solve this right now? 

Googling i'v found many people reporting problems like this on custom filestorages.

Thanks in advance!

**Comment by pkerpedjiev** [comment]
You can just add 'max_length` to the signature of `HasedFilenameStorage` and then ignore it:

```
        def save(self, name, content, max_length):
```

It doesn't get used for anything anyway.

**Comment by rebkwok** [comment]
Fixed by #7
