### ISSUE TITLE
incompatability with python3.5

### ISSUE THREAD

**Issue by Ibrahem3amer** [ecometrica/django-hashedfilenamestorage#8]
I got this AttributeError when using the package with Python3.5, django1.11.6

  File "path/site-packages/django_hashedfilenamestorage/storage.py", line 51, in _compute_hash
    hasher.update(data.encode('utf-8'))
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by rebkwok** [comment]
Fixed and released in v2.1
